import { PortfolioAlert } from '@/hooks/usePortfolioAlerts';

export const DEMO_PORTFOLIO_ALERTS: PortfolioAlert[] = [
  {
    id: 'demo-pa-1',
    user_id: 'demo-user',
    symbol: 'AAPL',
    alert_type: 'price_movement',
    threshold_percent: 5,
    is_active: true,
    triggered_at: null,
    trigger_value: null,
    notes: 'Monitor for significant price swings',
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-pa-2',
    user_id: 'demo-user',
    symbol: 'O',
    alert_type: 'dividend_cut',
    threshold_percent: null,
    is_active: true,
    triggered_at: null,
    trigger_value: null,
    notes: 'Monthly dividend REIT - watch for cuts',
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-pa-3',
    user_id: 'demo-user',
    symbol: 'JNJ',
    alert_type: 'dividend_increase',
    threshold_percent: null,
    is_active: true,
    triggered_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    trigger_value: 1.24,
    notes: 'Dividend aristocrat tracking',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-pa-4',
    user_id: 'demo-user',
    symbol: 'MSFT',
    alert_type: 'earnings_surprise',
    threshold_percent: null,
    is_active: true,
    triggered_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    trigger_value: 2.89,
    notes: 'Beat EPS estimates by 8%',
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-pa-5',
    user_id: 'demo-user',
    symbol: 'VZ',
    alert_type: 'price_movement',
    threshold_percent: 10,
    is_active: false,
    triggered_at: null,
    trigger_value: null,
    notes: 'Paused - reviewing position',
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-pa-6',
    user_id: 'demo-user',
    symbol: 'KO',
    alert_type: 'dividend_increase',
    threshold_percent: null,
    is_active: true,
    triggered_at: null,
    trigger_value: null,
    notes: '60+ years of dividend growth',
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
