import { Holding, AssetType } from '@/types';

/**
 * Demo holdings for preview mode - shows a diversified sample portfolio
 */
export const DEMO_HOLDINGS: Holding[] = [
  {
    id: 'demo-holding-1',
    symbol: 'AAPL',
    name: 'Apple Inc.',
    shares: 50,
    avgPrice: 145.00,
    currentPrice: 178.50,
    assetType: AssetType.STOCK,
    sector: 'Technology',
    country: 'US',
    dividendYield: 0.5,
    safetyScore: 85,
    snowflake: { value: 4, future: 4, past: 5, health: 5, dividend: 2, total: 4 },
  },
  {
    id: 'demo-holding-2',
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    shares: 30,
    avgPrice: 280.00,
    currentPrice: 378.20,
    assetType: AssetType.STOCK,
    sector: 'Technology',
    country: 'US',
    dividendYield: 0.8,
    safetyScore: 90,
    snowflake: { value: 3, future: 5, past: 5, health: 5, dividend: 2, total: 4 },
  },
  {
    id: 'demo-holding-3',
    symbol: 'JNJ',
    name: 'Johnson & Johnson',
    shares: 40,
    avgPrice: 150.00,
    currentPrice: 158.30,
    assetType: AssetType.STOCK,
    sector: 'Healthcare',
    country: 'US',
    dividendYield: 3.0,
    safetyScore: 88,
    snowflake: { value: 4, future: 3, past: 4, health: 4, dividend: 5, total: 4 },
  },
  {
    id: 'demo-holding-4',
    symbol: 'O',
    name: 'Realty Income Corporation',
    shares: 60,
    avgPrice: 52.00,
    currentPrice: 54.20,
    assetType: AssetType.ETF,
    sector: 'Real Estate',
    country: 'US',
    dividendYield: 5.8,
    safetyScore: 75,
    snowflake: { value: 4, future: 3, past: 3, health: 3, dividend: 5, total: 4 },
  },
  {
    id: 'demo-holding-5',
    symbol: 'KO',
    name: 'The Coca-Cola Company',
    shares: 100,
    avgPrice: 55.00,
    currentPrice: 58.90,
    assetType: AssetType.STOCK,
    sector: 'Consumer Staples',
    country: 'US',
    dividendYield: 3.1,
    safetyScore: 82,
    snowflake: { value: 3, future: 3, past: 4, health: 4, dividend: 5, total: 4 },
  },
  {
    id: 'demo-holding-6',
    symbol: 'PG',
    name: 'Procter & Gamble Co.',
    shares: 35,
    avgPrice: 140.00,
    currentPrice: 152.80,
    assetType: AssetType.STOCK,
    sector: 'Consumer Staples',
    country: 'US',
    dividendYield: 2.5,
    safetyScore: 86,
    snowflake: { value: 3, future: 3, past: 4, health: 5, dividend: 4, total: 4 },
  },
  {
    id: 'demo-holding-7',
    symbol: 'VZ',
    name: 'Verizon Communications Inc.',
    shares: 75,
    avgPrice: 42.00,
    currentPrice: 38.50,
    assetType: AssetType.STOCK,
    sector: 'Communication Services',
    country: 'US',
    dividendYield: 6.9,
    safetyScore: 70,
    snowflake: { value: 5, future: 2, past: 2, health: 3, dividend: 5, total: 3 },
  },
  {
    id: 'demo-holding-8',
    symbol: 'JPM',
    name: 'JPMorgan Chase & Co.',
    shares: 25,
    avgPrice: 135.00,
    currentPrice: 172.40,
    assetType: AssetType.STOCK,
    sector: 'Financials',
    country: 'US',
    dividendYield: 2.4,
    safetyScore: 80,
    snowflake: { value: 4, future: 4, past: 4, health: 4, dividend: 3, total: 4 },
  },
];

// Calculate demo portfolio total value
export const DEMO_PORTFOLIO_VALUE = DEMO_HOLDINGS.reduce(
  (sum, h) => sum + (h.shares * (h.currentPrice || h.avgPrice)),
  0
);

// Demo watchlist items
export const DEMO_WATCHLIST = [
  { id: 'demo-watch-1', symbol: 'NVDA', name: 'NVIDIA Corporation', target_price: 450.00, alert_enabled: true },
  { id: 'demo-watch-2', symbol: 'AMD', name: 'Advanced Micro Devices', target_price: 140.00, alert_enabled: false },
  { id: 'demo-watch-3', symbol: 'GOOGL', name: 'Alphabet Inc.', target_price: 150.00, alert_enabled: true },
  { id: 'demo-watch-4', symbol: 'AMZN', name: 'Amazon.com Inc.', target_price: 180.00, alert_enabled: false },
  { id: 'demo-watch-5', symbol: 'META', name: 'Meta Platforms Inc.', target_price: 500.00, alert_enabled: true },
];
