import { AppNotification, AppNotificationType } from '@/hooks/useNotifications';

/**
 * Demo notifications for preview mode
 */
export const DEMO_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'demo-notif-1',
    type: 'dividend' as AppNotificationType,
    actor_id: 'system',
    target_id: null,
    content: 'AAPL dividend of $0.25 per share will be paid on Mar 15, 2026. You hold 50 shares — expected income: $12.50.',
    is_read: false,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    actor_name: 'Dividend Tracker',
    actor_avatar: undefined,
  },
  {
    id: 'demo-notif-9',
    type: 'dividend' as AppNotificationType,
    actor_id: 'system',
    target_id: null,
    content: 'JNJ increased its quarterly dividend by 4.2% to $1.28/share — Dividend King status maintained (62 consecutive years).',
    is_read: false,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    actor_name: 'Dividend Alerts',
    actor_avatar: undefined,
  },
  {
    id: 'demo-notif-2',
    type: 'market_sync' as AppNotificationType,
    actor_id: 'system',
    target_id: null,
    content: 'Market data refreshed successfully. 8 holdings updated with current prices.',
    is_read: false,
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    actor_name: 'Market Sync',
    actor_avatar: undefined,
  },
  {
    id: 'demo-notif-3',
    type: 'tax' as AppNotificationType,
    actor_id: 'system',
    target_id: null,
    content: 'Tax loss harvesting opportunity: VZ is down 8.3% — consider selling to offset gains.',
    is_read: false,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    actor_name: 'Tax Advisor',
    actor_avatar: undefined,
  },
  {
    id: 'demo-notif-10',
    type: 'dividend' as AppNotificationType,
    actor_id: 'system',
    target_id: null,
    content: 'O (Realty Income) ex-dividend date is tomorrow. Monthly payout of $0.263/share — you\'ll receive $13.15 on 40 shares.',
    is_read: false,
    created_at: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
    actor_name: 'Dividend Tracker',
    actor_avatar: undefined,
  },
  {
    id: 'demo-notif-4',
    type: 'follower' as AppNotificationType,
    actor_id: 'demo-user-2',
    target_id: null,
    content: null,
    is_read: true,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    actor_name: 'Warren B.',
    actor_avatar: undefined,
  },
  {
    id: 'demo-notif-5',
    type: 'like' as AppNotificationType,
    actor_id: 'demo-user-3',
    target_id: 'demo-post-1',
    content: null,
    is_read: true,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    actor_name: 'Sarah K.',
    actor_avatar: undefined,
  },
  {
    id: 'demo-notif-6',
    type: 'comment' as AppNotificationType,
    actor_id: 'demo-user-4',
    target_id: 'demo-post-1',
    content: 'Great analysis on JNJ! I agree the dividend safety looks solid.',
    is_read: true,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    actor_name: 'Michael T.',
    actor_avatar: undefined,
  },
  {
    id: 'demo-notif-7',
    type: 'dividend' as AppNotificationType,
    actor_id: 'system',
    target_id: null,
    content: 'KO (Coca-Cola) paid $0.485/share on Mar 1. Total received: $24.25 on 50 shares — deposited to your account.',
    is_read: true,
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    actor_name: 'Dividend Tracker',
    actor_avatar: undefined,
  },
  {
    id: 'demo-notif-11',
    type: 'dividend' as AppNotificationType,
    actor_id: 'system',
    target_id: null,
    content: 'IIPR dividend yield rose to 8.2% — significantly above sector average of 3.9%. Review holding for risk assessment.',
    is_read: true,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    actor_name: 'Dividend Alerts',
    actor_avatar: undefined,
  },
  {
    id: 'demo-notif-12',
    type: 'dividend' as AppNotificationType,
    actor_id: 'system',
    target_id: null,
    content: 'PG (Procter & Gamble) confirmed 5.0% dividend increase — Dividend Aristocrat, 68 consecutive years of increases.',
    is_read: true,
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    actor_name: 'Dividend Alerts',
    actor_avatar: undefined,
  },
  {
    id: 'demo-notif-8',
    type: 'system' as AppNotificationType,
    actor_id: 'system',
    target_id: null,
    content: 'Welcome to WealthOS! Your portfolio is set up and ready to go.',
    is_read: true,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    actor_name: 'System',
    actor_avatar: undefined,
  },
];

// Calculate unread count for demo
export const DEMO_UNREAD_COUNT = DEMO_NOTIFICATIONS.filter(n => !n.is_read).length;
